config/routes.rb
Rails.application.routes.draw do
  root 'vices#all'
  resources :vices

end

app/models/vice.rb
class Vice < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true
  validates :category, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/vices_controller.rb
class VicesController < ApplicationController

  def new
    @vice = Vice.new
    # rt_key = ENV["rescue_time_api_key"] || ENV["api_key"]
    # rt_url = "https://www.rescuetime.com/anapi/data?key=#{rt_key}&format=json"
    # results = HTTParty.get(rt_url)
    # @options = results["rows"].map{|r| r[3]}.sort_by{|name| name.downcase}
    @options = ["Facebook",
                 "Gmail",
                 "localhost:3000",
                 "Pandora",
                 "swimminglongdistances.com",
                 "Github"].sort_by{|name| name.downcase}
    # populate a selection of sites from their api!!!!
  end

  def all
    @vices = Vice.all
  end

  def destroy
    Vice.delete(params["id"])
    redirect_to action: "all"
  end

  def create
    name = params["Name"]["name"] == "" ? nil : params["Name"]["name"]
    category = params["Category"]["category"] == "" ? nil : params["Category"]["category"]
    return redirect_to action: "new" unless name && category
    # get the category by hitting their api!!!
    Vice.create(name: name, category: category)
    redirect_to action: "all"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vice_helper.rb
module ViceHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RescueTimer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

</head>
<body>

<%= yield %>

</body>
</html>

app/views/vices/all.html.erb
<div class="col-md-4">
</div>
<div class="col-md-4">
<div class="row">
  <h1>Vice Dashboard</h1>
</div>
<div id="vice_manager">
  <div class="row">
    <h2 id="vice_manager_title">Vice Manager</h2>
  </div>
  <div class="row">
    <a class='btn btn-success' href='/vices/new'>Add a vice</button></a>
  </div>

  <div class="row">
    <table class="table table-bordered table-hover">
      <tr>
        <th id="site_header">Site</th>
        <th id="category_header">Category</th>
        <th></th>
      </tr
      <% @vices.each do |vice| %>
        <tr>
          <td class="name"><%= vice.name %></td>
          <td class="category"><%= vice.category %></td>
          <td><%= button_to "x", vice_path(:id => vice.id), :method => :delete, class: "inline btn btn-danger" %></td>
        </tr>
      <% end %>
      <tr>
      </tr>
    </table>
  </div>
</div>
<div id="time_manager">
  <h2>Time Manager</h2>
  <div><span>Weekly Allotment:</span><span id="total"><%= @total %></span></div>
  <div><span>Remaining Allotment:</span><span id="remaining"><%= @remaining %></span></div>
</div>
</div>

app/views/vices/new.html.erb
<div class="col-md-4">
</div>
<div class="col-md-4">
<div class="row">

  <h1>New Vice</h1>
  <%= form_for @vice, url: {action: "create"}, html: {class: "new_vice_form"} do |f| %>
    <%= label_tag(:q, "Name:") %>
    <%= select("Name", "name", @options, {:include_blank => true}) %>
    <%= select("Category", "category", ["Glancer","Engrosser"], {:include_blank => true}) %>
    <%= f.submit "Save", class:"btn btn-success" %>
  <% end %>
</div>
</div>